% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  12pt,
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={US Consumption Forecast},
  pdfauthor={Jiyoon Moon},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage[T1]{fontenc} \usepackage[utf8]{inputenc} \usepackage{lmodern} \usepackage{lipsum} \usepackage{fancyhdr} \pagestyle{fancy} \renewcommand{\headrulewidth}{0pt} \fancyhf{} \fancyfoot[C]{\twopagenumbers} \fancypagestyle{plain}{ \renewcommand{\headrulewidth}{0pt} \fancyhf{} \fancyfoot[C]{\twopagenumbers} } \usepackage[user]{zref} \newcounter{pageaux} \def\currentauxref{PAGEAUX1} \newcommand{\twopagenumbers}{ \stepcounter{pageaux} \thepageaux\, of\, \ref{\currentauxref} } \makeatletter \newcommand{\resetpageaux}{ \clearpage \edef\@currentlabel{\thepageaux}\label{\currentauxref} \xdef\currentauxref{PAGEAUX\thepage} \setcounter{pageaux}{0}} \AtEndDvi{\edef\@currentlabel{\thepageaux}\label{\currentauxref}} \makeatletter
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{US Consumption Forecast}
\author{Jiyoon Moon}
\date{Last compiled on: 11 June, 2025}

\begin{document}
\maketitle
\begin{abstract}
This report analyzes quarterly US consumption data using multiple time
series models. Both ARIMA-based and regression-based models are
evaluated to understand the drivers of consumption and to forecast its
behavior in the near future. External variables such as income,
production, and unemployment are explored to improve forecast accuracy.
\end{abstract}

\thispagestyle{empty}
\newpage
\setcounter{page}{1}

\hypertarget{time-series-analysis-and-eda}{%
\subsection{1. Time Series Analysis and
EDA}\label{time-series-analysis-and-eda}}

\begin{figure}
\centering
\includegraphics{us-consumption-forecast_files/figure-latex/fig-consumption-ts-1.pdf}
\caption{US Consumption Time Series (1970--2014)}
\end{figure}

The top panel of Figure 1 shows the time series of US Consumption from
1970 to 2014. The series shows no clear seasonality but fluctuates
moderately over time, with alternating periods of mild increases and
decreases, a sharp dip around 2008--2009 likely due to the Global
Financial Crisis, and an overall appearance of stationarity with minor
changes in trend and volatility. The ACF shows significant
autocorrelation at lags 1 to 3 and then drops off sharply at lag 4,
indicating a potential MA(3) structure, while the PACF gradually
decreases without a clear cut-off, which is also characteristic of a
moving average (MA) process rather than an autoregressive one.

\begin{figure}
\includegraphics[width=0.49\linewidth]{us-consumption-forecast_files/figure-latex/fig-consumption-income-1} \includegraphics[width=0.49\linewidth]{us-consumption-forecast_files/figure-latex/fig-consumption-income-2} \caption{Quarterly US Consumption and Income Over Time}\label{fig:fig-consumption-income}
\end{figure}

Figure 2 shows the quarterly evolution of US consumption and income.
Consumption remains relatively stable over time, with no clear upward or
downward trend. It fluctuates around a consistent level, with noticeable
drops around 2008 likely due to the global financial crisis. Income also
shows mild variation across quarters, without a strong long-term
increase.

\hypertarget{model}{%
\subsection{2. Model}\label{model}}

\hypertarget{model-1-arima003}{%
\subsubsection{Model 1) ARIMA(0,0,3)}\label{model-1-arima003}}

\begin{figure}
\includegraphics[width=0.49\linewidth]{us-consumption-forecast_files/figure-latex/fig-arima-003-diagnostics-1} \includegraphics[width=0.49\linewidth]{us-consumption-forecast_files/figure-latex/fig-arima-003-diagnostics-2} \caption{Residuals and Forecast - ARIMA(0,0,3)}\label{fig:fig-arima-003-diagnostics}
\end{figure}

The ACF plot shows a sharp drop after lag 3, while the PACF declines
gradually across lags 1 to 3 with no significant spikes beyond,
suggesting an MA(3) structure. Based on this, the ARIMA(0,0,3) model was
selected. The residuals resemble white noise, indicating a good fit, and
the forecast closely matches the actual test values within appropriate
prediction intervals. This model is simple, interpretable, and reliable
for short-term forecasting, with a training RMSE of about 0.60 and a
test RMSE of 0.24.

\hypertarget{model-2-arima3002004}{%
\subsubsection{Model 2)
ARIMA(3,0,0)(2,0,0){[}4{]}}\label{model-2-arima3002004}}

\begin{figure}
\includegraphics[width=0.49\linewidth]{us-consumption-forecast_files/figure-latex/fig-arima-300-200-4-diagnostics-1} \includegraphics[width=0.49\linewidth]{us-consumption-forecast_files/figure-latex/fig-arima-300-200-4-diagnostics-2} \caption{Residuals and Forecast - ARIMA(3,0,0)(2,0,0)[4]}\label{fig:fig-arima-300-200-4-diagnostics}
\end{figure}

The model includes both non-seasonal AR(3) and seasonal AR(2) terms
which were selected based on significant PACF spikes at lags 1--3 and
the presence of quarterly seasonality. It performs well, with residuals
resembling white noise and delivering high forecast accuracy. The
ARIMA(3,0,0)(2,0,0){[}4{]} model effectively captures both seasonal and
autoregressive dynamics and is suitable for short-term prediction with a
test RMSE of approximately 0.27.

\hypertarget{model-3-regression-with-arima1110014-errors}{%
\subsubsection{Model 3) Regression with ARIMA(1,1,1)(0,0,1){[}4{]}
Errors}\label{model-3-regression-with-arima1110014-errors}}

\begin{figure}
\includegraphics[width=0.49\linewidth]{us-consumption-forecast_files/figure-latex/fig-arimax-diagnostics-1} \includegraphics[width=0.49\linewidth]{us-consumption-forecast_files/figure-latex/fig-arimax-diagnostics-2} \caption{Residuals and Forecast - ARIMAX (Income + Unemployment)}\label{fig:fig-arimax-diagnostics}
\end{figure}

The dynamic regression model uses Income and Unemployment as regressors
while implementing an ARIMA(1,1,1)(0,0,1){[}4{]} structure for error
modeling which automatically detects both explanatory and seasonal
components. The model shows well-behaved residuals and strong forecast
performance and the external regressors improve the accuracy. The ARIMAX
specification among all models tested provides the best balance of
accuracy and interpretability with the lowest test RMSE (0.24) and MAE
(0.17) which indicates robust out-of-sample performance.

\hypertarget{model-comparison-and-conclusion}{%
\subsection{3. Model Comparison and
Conclusion}\label{model-comparison-and-conclusion}}

\begin{longtable}[]{@{}lrrrr@{}}
\caption{Comparison of three models}\tabularnewline
\toprule
Model & Test.RMSE & Test.MAE & Theil.s.U & Ljung.Box.p.value \\
\midrule
\endfirsthead
\toprule
Model & Test.RMSE & Test.MAE & Theil.s.U & Ljung.Box.p.value \\
\midrule
\endhead
ARIMA(0,0,3) & 0.2401 & 0.2153 & 0.6391 & 0.1297 \\
ARIMA(3,0,0)(2,0,0){[}4{]} & 0.2747 & 0.2482 & 0.7365 & 0.8787 \\
ARIMAX(1,1,1)(0,0,1){[}4{]} & 0.2374 & 0.1687 & 0.8030 & 0.1703 \\
\bottomrule
\end{longtable}

The ARIMAX(1,1,1)(0,0,1){[}4{]} model produced the lowest RMSE value of
0.237 and the lowest MAE value of 0.169 which indicates its best
out-of-sample prediction accuracy. The Theil's U value of this model was
slightly higher than others but it still indicates good forecast
performance. The ARIMAX(1,1,1)(0,0,1){[}4{]} model with Income and
Unemployment variables should be recommended because it provides the
best accuracy and economic interpretability. However, there are
limitations: only two external variables were included, the models
assumed linearity which may overlook complex patterns, structural breaks
or shocks were not accounted for, and the static training/testing split
could limit generalizability. Future improvements may involve adding
more macroeconomic predictors (e.g., interest rate, inflation),
exploring non-linear or machine learning approaches, and incorporating
structural break detection or rolling forecast evaluations.

\newpage
\thispagestyle{empty}
\begin{center}
\Huge \bf [END of the REPORT]
\end{center}

\newpage

\clearpage \edef\@currentlabel{\thepageaux}\label{PAGEAUX1} \xdef PAGEAUX1{PAGEAUX\thepage} \setcounter{pageaux}{0}
\renewcommand{\thepageaux}{R-\arabic{pageaux}}

\hypertarget{r-code}{%
\section{R code}\label{r-code}}

\hypertarget{question-1-consumption-time-series-analysis}{%
\section{Question 1: Consumption Time Series
Analysis}\label{question-1-consumption-time-series-analysis}}

\hypertarget{a-data-splitting}{%
\subsection{(a) Data Splitting}\label{a-data-splitting}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load the uschange dataset from fpp2 package}
\FunctionTok{data}\NormalTok{(}\StringTok{"uschange"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Split the dataset into training (1970 Q1 to 2014 Q4) and test (2015 Q1 to 2016 Q3)}
\NormalTok{train }\OtherTok{\textless{}{-}} \FunctionTok{window}\NormalTok{(uschange, }\AttributeTok{end=}\FunctionTok{c}\NormalTok{(}\DecValTok{2014}\NormalTok{,}\DecValTok{4}\NormalTok{))}
\NormalTok{test  }\OtherTok{\textless{}{-}} \FunctionTok{window}\NormalTok{(uschange, }\AttributeTok{start=}\FunctionTok{c}\NormalTok{(}\DecValTok{2015}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\hypertarget{b-exploratory-data-analysis-eda}{%
\subsection{(b) Exploratory Data Analysis
(EDA)}\label{b-exploratory-data-analysis-eda}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Summary statistics of training data}
\FunctionTok{summary}\NormalTok{(train)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Consumption          Income          Production         Savings       
##  Min.   :-2.2741   Min.   :-4.2652   Min.   :-6.8510   Min.   :-68.788  
##  1st Qu.: 0.4159   1st Qu.: 0.2833   1st Qu.: 0.1429   1st Qu.: -4.820  
##  Median : 0.7888   Median : 0.7232   Median : 0.6979   Median :  1.133  
##  Mean   : 0.7493   Mean   : 0.7185   Mean   : 0.5377   Mean   :  1.215  
##  3rd Qu.: 1.1083   3rd Qu.: 1.1727   3rd Qu.: 1.3420   3rd Qu.:  7.065  
##  Max.   : 2.3183   Max.   : 4.5365   Max.   : 4.1496   Max.   : 50.758  
##   Unemployment     
##  Min.   :-0.90000  
##  1st Qu.:-0.20000  
##  Median : 0.00000  
##  Mean   : 0.01167  
##  3rd Qu.: 0.10000  
##  Max.   : 1.40000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Check for missing values}
\FunctionTok{colSums}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(train))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Consumption       Income   Production      Savings Unemployment 
##            0            0            0            0            0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Visualizing Consumption over time}
\NormalTok{train\_df }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(train)  }\CommentTok{\# Convert ts to data frame for ggplot}
\NormalTok{train\_df}\SpecialCharTok{$}\NormalTok{Date }\OtherTok{\textless{}{-}} \FunctionTok{time}\NormalTok{(train)      }\CommentTok{\# Add time column for plotting}

\FunctionTok{ggplot}\NormalTok{(train\_df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Date, }\AttributeTok{y =}\NormalTok{ Consumption)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{color =} \StringTok{"steelblue"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Quarterly US Consumption Over Time"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{size =} \DecValTok{12}\NormalTok{),}
        \AttributeTok{axis.text.y =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{size =} \DecValTok{12}\NormalTok{),}
        \AttributeTok{title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{size =} \DecValTok{16}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{us-consumption-forecast_files/figure-latex/eda-plot-consumption-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Visualizing average Income over time}
\CommentTok{\# Although ts is evenly spaced, we emulate the behavior of previous project EDA}

\FunctionTok{ggplot}\NormalTok{(train\_df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Date, }\AttributeTok{y =}\NormalTok{ Income)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{color =} \StringTok{"darkgreen"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Quarterly US Income Over Time"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{size =} \DecValTok{12}\NormalTok{),}
        \AttributeTok{axis.text.y =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{size =} \DecValTok{12}\NormalTok{),}
        \AttributeTok{title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{size =} \DecValTok{16}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{us-consumption-forecast_files/figure-latex/eda-aggregate-income-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calculate correlation matrix to assess variable relationships}
\FunctionTok{cor}\NormalTok{(train)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              Consumption     Income  Production     Savings Unemployment
## Consumption    1.0000000  0.3989102  0.54879015 -0.23931232   -0.5439411
## Income         0.3989102  1.0000000  0.27944720  0.71379623   -0.2312733
## Production     0.5487901  0.2794472  1.00000000 -0.06811485   -0.7989555
## Savings       -0.2393123  0.7137962 -0.06811485  1.00000000    0.1109808
## Unemployment  -0.5439411 -0.2312733 -0.79895549  0.11098078    1.0000000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ACF and PACF plots to assess autocorrelation and potential ARIMA components}
\FunctionTok{tsdisplay}\NormalTok{(train[, }\StringTok{"Consumption"}\NormalTok{], }\AttributeTok{main =} \StringTok{"Consumption Time Series Diagnostics"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{us-consumption-forecast_files/figure-latex/eda-acf-pacf-1.pdf}

\hypertarget{c-model-fitting-and-forecasting}{%
\subsection{(c) Model Fitting and
Forecasting}\label{c-model-fitting-and-forecasting}}

\hypertarget{model-selection-arima003}{%
\subsubsection{1) Model Selection:
ARIMA(0,0,3)}\label{model-selection-arima003}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Fit ARIMA(0,0,3) model (pure MA(3) model)}
\NormalTok{fit\_ma3 }\OtherTok{\textless{}{-}} \FunctionTok{Arima}\NormalTok{(train[,}\StringTok{"Consumption"}\NormalTok{], }\AttributeTok{order =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{3}\NormalTok{))}

\CommentTok{\# Display model summary: coefficients, AIC, etc.}
\FunctionTok{summary}\NormalTok{(fit\_ma3)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Series: train[, "Consumption"] 
## ARIMA(0,0,3) with non-zero mean 
## 
## Coefficients:
##          ma1     ma2     ma3    mean
##       0.2435  0.2183  0.2679  0.7517
## s.e.  0.0733  0.0734  0.0648  0.0768
## 
## sigma^2 = 0.366:  log likelihood = -163.07
## AIC=336.15   AICc=336.49   BIC=352.11
## 
## Training set error measures:
##                         ME      RMSE       MAE      MPE     MAPE      MASE
## Training set -5.533779e-05 0.5981964 0.4416385 83.09945 209.9472 0.6756687
##                    ACF1
## Training set 0.01392546
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Check if residuals are white noise (no autocorrelation)}
\FunctionTok{checkresiduals}\NormalTok{(fit\_ma3)}
\end{Highlighting}
\end{Shaded}

\includegraphics{us-consumption-forecast_files/figure-latex/fit-arima_003-1.pdf}

\begin{verbatim}
## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(0,0,3) with non-zero mean
## Q* = 8.5225, df = 5, p-value = 0.1297
## 
## Model df: 3.   Total lags used: 8
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Forecast 7 steps ahead (to match test set)}
\NormalTok{fc\_ma3 }\OtherTok{\textless{}{-}} \FunctionTok{forecast}\NormalTok{(fit\_ma3, }\AttributeTok{h =} \DecValTok{7}\NormalTok{)}

\CommentTok{\# Plot forecast with actual test values}
\FunctionTok{autoplot}\NormalTok{(fc\_ma3) }\SpecialCharTok{+}
  \FunctionTok{autolayer}\NormalTok{(test[,}\StringTok{"Consumption"}\NormalTok{], }\AttributeTok{series =} \StringTok{"Actual"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Forecast using ARIMA(0,0,3) (MA(3)) model"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Consumption"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Time"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{us-consumption-forecast_files/figure-latex/forecast-arima_003-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Compare forecast to test set}
\FunctionTok{accuracy}\NormalTok{(fc\_ma3, test[,}\StringTok{"Consumption"}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                         ME      RMSE       MAE       MPE      MAPE      MASE
## Training set -5.533779e-05 0.5981964 0.4416385  83.09945 209.94724 0.6756687
## Test set     -1.307562e-01 0.2400561 0.2153278 -28.09347  36.16553 0.3294329
##                     ACF1 Theil's U
## Training set  0.01392546        NA
## Test set     -0.09102033 0.6391078
\end{verbatim}

\hypertarget{model-selection-arima3002004}{%
\subsubsection{2) Model Selection:
ARIMA(3,0,0)(2,0,0){[}4{]}}\label{model-selection-arima3002004}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Fit an ARIMA model automatically selected by AICc}
\NormalTok{fit\_auto }\OtherTok{\textless{}{-}} \FunctionTok{auto.arima}\NormalTok{(train[,}\StringTok{"Consumption"}\NormalTok{])}

\CommentTok{\# Display summary of the automatically selected model}
\FunctionTok{summary}\NormalTok{(fit\_auto)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Series: train[, "Consumption"] 
## ARIMA(3,0,0)(2,0,0)[4] with non-zero mean 
## 
## Coefficients:
##          ar1     ar2     ar3     sar1     sar2    mean
##       0.2271  0.1777  0.2200  -0.0334  -0.1803  0.7522
## s.e.  0.0737  0.0736  0.0724   0.0772   0.0744  0.0946
## 
## sigma^2 = 0.353:  log likelihood = -158.94
## AIC=331.88   AICc=332.53   BIC=354.23
## 
## Training set error measures:
##                        ME      RMSE       MAE      MPE     MAPE     MASE
## Training set 0.0002895183 0.5841338 0.4391314 65.53638 188.5312 0.671833
##                     ACF1
## Training set 0.009685967
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Residual diagnostics: check whether residuals are uncorrelated and normally distributed}
\FunctionTok{checkresiduals}\NormalTok{(fit\_auto)}
\end{Highlighting}
\end{Shaded}

\includegraphics{us-consumption-forecast_files/figure-latex/fit-ARIMA_300_200_4-1.pdf}

\begin{verbatim}
## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(3,0,0)(2,0,0)[4] with non-zero mean
## Q* = 0.67677, df = 3, p-value = 0.8787
## 
## Model df: 5.   Total lags used: 8
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Forecast 7 steps ahead using the auto.arima model}
\NormalTok{fc\_auto }\OtherTok{\textless{}{-}} \FunctionTok{forecast}\NormalTok{(fit\_auto, }\AttributeTok{h =} \DecValTok{7}\NormalTok{)}

\CommentTok{\# Plot forecast and overlay actual test values}
\FunctionTok{autoplot}\NormalTok{(fc\_auto) }\SpecialCharTok{+}
  \FunctionTok{autolayer}\NormalTok{(test[,}\StringTok{"Consumption"}\NormalTok{], }\AttributeTok{series =} \StringTok{"Actual"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Forecast from auto.arima Model"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Consumption"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Time"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{us-consumption-forecast_files/figure-latex/forecast-ARIMA_300_200_4-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Evaluate forecast accuracy against the test set}
\FunctionTok{accuracy}\NormalTok{(fc\_auto, test[,}\StringTok{"Consumption"}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                         ME      RMSE       MAE       MPE      MAPE      MASE
## Training set  0.0002895183 0.5841338 0.4391314  65.53638 188.53118 0.6718330
## Test set     -0.1651797648 0.2746917 0.2481962 -34.54071  42.46434 0.3797188
##                      ACF1 Theil's U
## Training set  0.009685967        NA
## Test set     -0.085512024 0.7365495
\end{verbatim}

\hypertarget{model-selection-regression-with-arima1110014-errors}{%
\subsubsection{3) Model Selection: Regression with
ARIMA(1,1,1)(0,0,1){[}4{]}
Errors}\label{model-selection-regression-with-arima1110014-errors}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Fit ARIMA model with external regressors: Income and Unemployment}
\CommentTok{\# This is a dynamic regression model with ARIMA errors}
\NormalTok{xreg\_train }\OtherTok{\textless{}{-}} \FunctionTok{as.matrix}\NormalTok{(train[, }\FunctionTok{c}\NormalTok{(}\StringTok{"Income"}\NormalTok{, }\StringTok{"Unemployment"}\NormalTok{)])}
\NormalTok{xreg\_test }\OtherTok{\textless{}{-}} \FunctionTok{as.matrix}\NormalTok{(test[, }\FunctionTok{c}\NormalTok{(}\StringTok{"Income"}\NormalTok{, }\StringTok{"Unemployment"}\NormalTok{)])}

\NormalTok{fit\_arimax }\OtherTok{\textless{}{-}} \FunctionTok{auto.arima}\NormalTok{(train[,}\StringTok{"Consumption"}\NormalTok{], }\AttributeTok{xreg =}\NormalTok{ xreg\_train)}

\CommentTok{\# Show model summary}
\FunctionTok{summary}\NormalTok{(fit\_arimax)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Series: train[, "Consumption"] 
## Regression with ARIMA(1,1,1)(0,0,1)[4] errors 
## 
## Coefficients:
##           ar1      ma1     sma1  Income  Unemployment
##       -0.1261  -0.8024  -0.1998  0.1592       -0.9085
## s.e.   0.1197   0.1041   0.0994  0.0440        0.1095
## 
## sigma^2 = 0.2706:  log likelihood = -135.27
## AIC=282.53   AICc=283.02   BIC=301.66
## 
## Training set error measures:
##                       ME      RMSE     MAE      MPE     MAPE      MASE
## Training set -0.02826937 0.5114767 0.39035 29.05286 169.1049 0.5972017
##                      ACF1
## Training set 0.0009526163
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Residual diagnostics}
\FunctionTok{checkresiduals}\NormalTok{(fit\_arimax)}
\end{Highlighting}
\end{Shaded}

\includegraphics{us-consumption-forecast_files/figure-latex/fit-ARIMAX-1.pdf}

\begin{verbatim}
## 
##  Ljung-Box test
## 
## data:  Residuals from Regression with ARIMA(1,1,1)(0,0,1)[4] errors
## Q* = 7.7544, df = 5, p-value = 0.1703
## 
## Model df: 3.   Total lags used: 8
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Forecast next 7 quarters using test xreg data}
\NormalTok{fc\_arimax }\OtherTok{\textless{}{-}} \FunctionTok{forecast}\NormalTok{(fit\_arimax, }\AttributeTok{xreg =}\NormalTok{ xreg\_test, }\AttributeTok{h =} \DecValTok{7}\NormalTok{)}

\CommentTok{\# Plot forecast with actual values}
\FunctionTok{autoplot}\NormalTok{(fc\_arimax) }\SpecialCharTok{+}
  \FunctionTok{autolayer}\NormalTok{(test[,}\StringTok{"Consumption"}\NormalTok{], }\AttributeTok{series =} \StringTok{"Actual"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Forecast using ARIMA with Income and Unemployment as Regressors"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{us-consumption-forecast_files/figure-latex/forecast-ARIMAX-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Forecast accuracy on test set}
\FunctionTok{accuracy}\NormalTok{(fc\_arimax, test[,}\StringTok{"Consumption"}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                       ME      RMSE       MAE      MPE      MAPE      MASE
## Training set -0.02826937 0.5114767 0.3903500 29.05286 169.10494 0.5972017
## Test set      0.15550625 0.2374365 0.1687326 19.30715  21.77719 0.2581463
##                       ACF1 Theil's U
## Training set  0.0009526163        NA
## Test set     -0.0077286118 0.8029547
\end{verbatim}

\end{document}
